"""baseline: the schema as it stood at the first deployment

Every table this application has, as of the first box it was deployed to. Generated from the models
rather than written by hand, so it says exactly what `Base.metadata.create_all` was saying.

**On a database that already holds the corpus, do not run this.** Run `orderorder migrate --stamp`
instead: the tables are already there, and stamping records that this revision has been applied
without trying to apply it. On an empty database `orderorder migrate` runs it and the result is the
schema `init_db` used to create.

Revision ID: c56da0a58c0b
Revises:
Created: 2026-09-08
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'c56da0a58c0b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brief',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('matter_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('facts', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brief', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brief_matter_id'), ['matter_id'], unique=False)

    op.create_table('job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_status'), ['status'], unique=False)

    op.create_table('judgment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_key', sa.String(length=80), nullable=False),
    sa.Column('court', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('decided_on', sa.Date(), nullable=True),
    sa.Column('neutral_citation', sa.String(length=64), nullable=True),
    sa.Column('bench_strength', sa.Integer(), nullable=True),
    sa.Column('judges', sa.JSON(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('judgment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_judgment_canonical_key'), ['canonical_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_judgment_court'), ['court'], unique=False)
        batch_op.create_index(batch_op.f('ix_judgment_decided_on'), ['decided_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_judgment_neutral_citation'), ['neutral_citation'], unique=False)
        batch_op.create_index(batch_op.f('ix_judgment_source_id'), ['source_id'], unique=False)

    op.create_table('brief_citation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('brief_id', sa.String(length=36), nullable=False),
    sa.Column('raw', sa.String(length=200), nullable=False),
    sa.Column('normalized', sa.String(length=160), nullable=True),
    sa.Column('span_start', sa.Integer(), nullable=False),
    sa.Column('span_end', sa.Integer(), nullable=False),
    sa.Column('claimed_pinpoint', sa.String(length=32), nullable=True),
    sa.Column('proposition', sa.Text(), nullable=True),
    sa.Column('judgment_id', sa.String(length=36), nullable=True),
    sa.Column('resolution', sa.String(length=16), nullable=False),
    sa.Column('resolution_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['brief_id'], ['brief.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judgment_id'], ['judgment.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brief_citation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brief_citation_brief_id'), ['brief_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brief_citation_judgment_id'), ['judgment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brief_citation_normalized'), ['normalized'], unique=False)

    op.create_table('citation_alias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('judgment_id', sa.String(length=36), nullable=False),
    sa.Column('reporter', sa.String(length=24), nullable=False),
    sa.Column('citation_string', sa.String(length=160), nullable=False),
    sa.Column('normalized', sa.String(length=160), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['judgment_id'], ['judgment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized', name='uq_citation_alias_normalized')
    )
    with op.batch_alter_table('citation_alias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_citation_alias_judgment_id'), ['judgment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_citation_alias_normalized'), ['normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_citation_alias_reporter'), ['reporter'], unique=False)

    op.create_table('judgment_text_version',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('judgment_id', sa.String(length=36), nullable=False),
    sa.Column('version_key', sa.String(length=96), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('ocr_derived', sa.Boolean(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('preferred', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['judgment_id'], ['judgment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('judgment_id', 'version_key', name='uq_text_version')
    )
    with op.batch_alter_table('judgment_text_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_judgment_text_version_judgment_id'), ['judgment_id'], unique=False)

    op.create_table('judgment_digest',
    sa.Column('judgment_id', sa.String(length=36), nullable=False),
    sa.Column('text_version_id', sa.String(length=36), nullable=True),
    sa.Column('digest', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=96), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['judgment_id'], ['judgment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['text_version_id'], ['judgment_text_version.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('judgment_id')
    )
    op.create_table('opinion',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('text_version_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('author', sa.String(length=160), nullable=True),
    sa.Column('seq_start', sa.Integer(), nullable=False),
    sa.Column('seq_end', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['text_version_id'], ['judgment_text_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opinion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opinion_text_version_id'), ['text_version_id'], unique=False)

    op.create_table('paragraph_alias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_version_id', sa.String(length=36), nullable=False),
    sa.Column('from_label', sa.String(length=16), nullable=False),
    sa.Column('to_version_id', sa.String(length=36), nullable=False),
    sa.Column('to_label', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['from_version_id'], ['judgment_text_version.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_version_id'], ['judgment_text_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verdict',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('brief_citation_id', sa.String(length=36), nullable=False),
    sa.Column('existence', sa.String(length=16), nullable=False),
    sa.Column('location_status', sa.String(length=16), nullable=True),
    sa.Column('support', sa.String(length=16), nullable=True),
    sa.Column('voice', sa.String(length=24), nullable=True),
    sa.Column('weight', sa.String(length=16), nullable=True),
    sa.Column('treatment', sa.String(length=32), nullable=True),
    sa.Column('applicability', sa.String(length=16), nullable=True),
    sa.Column('grade', sa.String(length=2), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=96), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brief_citation_id'], ['brief_citation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verdict', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verdict_brief_citation_id'), ['brief_citation_id'], unique=False)

    op.create_table('paragraph',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('text_version_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('printed_label', sa.String(length=16), nullable=True),
    sa.Column('opinion_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opinion_id'], ['opinion.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['text_version_id'], ['judgment_text_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text_version_id', 'seq', name='uq_paragraph_seq')
    )
    with op.batch_alter_table('paragraph', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paragraph_text_version_id'), ['text_version_id'], unique=False)
        batch_op.create_index('ix_paragraph_version_label', ['text_version_id', 'printed_label'], unique=False)

    op.create_table('citation_edge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('citing_id', sa.String(length=36), nullable=False),
    sa.Column('cited_id', sa.String(length=36), nullable=True),
    sa.Column('cited_alias', sa.String(length=160), nullable=True),
    sa.Column('treatment', sa.String(length=32), nullable=True),
    sa.Column('paragraph_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cited_id'], ['judgment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['citing_id'], ['judgment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paragraph_id'], ['paragraph.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('citation_edge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_citation_edge_cited_id'), ['cited_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_citation_edge_citing_id'), ['citing_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citation_edge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citation_edge_citing_id'))
        batch_op.drop_index(batch_op.f('ix_citation_edge_cited_id'))

    op.drop_table('citation_edge')
    with op.batch_alter_table('paragraph', schema=None) as batch_op:
        batch_op.drop_index('ix_paragraph_version_label')
        batch_op.drop_index(batch_op.f('ix_paragraph_text_version_id'))

    op.drop_table('paragraph')
    with op.batch_alter_table('verdict', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verdict_brief_citation_id'))

    op.drop_table('verdict')
    op.drop_table('paragraph_alias')
    with op.batch_alter_table('opinion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opinion_text_version_id'))

    op.drop_table('opinion')
    op.drop_table('judgment_digest')
    with op.batch_alter_table('judgment_text_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_judgment_text_version_judgment_id'))

    op.drop_table('judgment_text_version')
    with op.batch_alter_table('citation_alias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citation_alias_reporter'))
        batch_op.drop_index(batch_op.f('ix_citation_alias_normalized'))
        batch_op.drop_index(batch_op.f('ix_citation_alias_judgment_id'))

    op.drop_table('citation_alias')
    with op.batch_alter_table('brief_citation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brief_citation_normalized'))
        batch_op.drop_index(batch_op.f('ix_brief_citation_judgment_id'))
        batch_op.drop_index(batch_op.f('ix_brief_citation_brief_id'))

    op.drop_table('brief_citation')
    with op.batch_alter_table('judgment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_judgment_source_id'))
        batch_op.drop_index(batch_op.f('ix_judgment_neutral_citation'))
        batch_op.drop_index(batch_op.f('ix_judgment_decided_on'))
        batch_op.drop_index(batch_op.f('ix_judgment_court'))
        batch_op.drop_index(batch_op.f('ix_judgment_canonical_key'))

    op.drop_table('judgment')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_status'))
        batch_op.drop_index(batch_op.f('ix_job_kind'))

    op.drop_table('job')
    with op.batch_alter_table('brief', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brief_matter_id'))

    op.drop_table('brief')
    # ### end Alembic commands ###
